// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdnZcicPu59TFUr9tDR0Ye8cvrZwK7As',
    appId: '1:264523627999:web:110975039747c2513c586a',
    messagingSenderId: '264523627999',
    projectId: 'movies-app-7acc0',
    authDomain: 'movies-app-7acc0.firebaseapp.com',
    storageBucket: 'movies-app-7acc0.firebasestorage.app',
    measurementId: 'G-P6YNNJZED7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFjoam82oxkLP5jko0mKRIvLhpV4uAOy8',
    appId: '1:264523627999:android:e2959b0c5c3611583c586a',
    messagingSenderId: '264523627999',
    projectId: 'movies-app-7acc0',
    storageBucket: 'movies-app-7acc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB12fNc1bjeujpcgFdUAEiXAGl1I6bMZ1Q',
    appId: '1:264523627999:ios:7ea2baea180442523c586a',
    messagingSenderId: '264523627999',
    projectId: 'movies-app-7acc0',
    storageBucket: 'movies-app-7acc0.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB12fNc1bjeujpcgFdUAEiXAGl1I6bMZ1Q',
    appId: '1:264523627999:ios:7ea2baea180442523c586a',
    messagingSenderId: '264523627999',
    projectId: 'movies-app-7acc0',
    storageBucket: 'movies-app-7acc0.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfdnZcicPu59TFUr9tDR0Ye8cvrZwK7As',
    appId: '1:264523627999:web:21036b2d070d01c53c586a',
    messagingSenderId: '264523627999',
    projectId: 'movies-app-7acc0',
    authDomain: 'movies-app-7acc0.firebaseapp.com',
    storageBucket: 'movies-app-7acc0.firebasestorage.app',
    measurementId: 'G-F36C382TY5',
  );
}
